name: Github CI Example

on:
  push:
  pull_request:
    branches:
      - main


jobs:
  unit_test:
    name: Run Analyze and Unit Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter test

      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json

      - uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: './coverage/lcov.info'
          min_coverage: 80
          exclude: '**/*_observer.dart **/change.dart'
  
  integration_test:
    name: Run Integration Tests

    needs:
      - unit_test

    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [29]
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          profile: Nexus 6
          script: flutter test integration_test

          
