name: Github CI/CD Example

on:
  push:
    tags:
      - "*"

jobs:
  unit_test:
    name: Run Analyze and Unit Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter test

      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json

      - uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: './coverage/lcov.info'
          min_coverage: 0
          exclude: '**/*_observer.dart **/change.dart'
  
  build_android:
    name: Build App - Android

    needs:
      - unit_test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with: 
          java-version: "12.x"
      
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter clean

      - run: flutter build apk --release

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
          
  build_ios:
    name: Build App - iOS

    needs:
      - unit_test

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter clean

      - run: flutter build ios lib/main.dart --release --no-codesign

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/iphoneos/*.ipa"
          token: ${{ secrets.TOKEN }}
          